### ISSUE TITLE
ActorExitRequest() does not appear to exit until next ping?

### ISSUE THREAD

**Issue by Bazmundi** [kquick/Thespian#16]
ActorExitRequest() seems to need a subsequent request?

Using hello world example:

```
hello = ActorSystem().createActor(Hello)
print(ActorSystem().ask(hello, 'hi', 1))
Hello, World!
ActorSystem().tell(hello, ActorExitRequest())
print(ActorSystem().ask(hello, 'hi', 1))
Hello, World!
print(ActorSystem().ask(hello, 'hi', 1))
None
```

**Comment by kquick** [comment]
Hi @Bazmundi,

You didn't include the body of your Hello actor, so I'm assuming you are using the one in the "Quick Start" documentation:

```
class Hello(Actor):
    def receiveMessage(self, message, sender):
        self.send(sender, 'Hello, World!')
```

There is a subtle interplay occurring here:
  * An actor is always called with the ActorExitRequest message.  This allows it to perform shutdown activities, but when the receiveMessage method returns to the caller, the Actor will then be destroyed.
  * The messages sent to any other Actor, or to the external requestor are queued for the recipient.

Thus, what is happening in your report is:
   1. Hello actor is created
   2. REPL uses `ask()` to send 'hi' to the Hello actor and wait for a response
   3. Hello actor gets the message and sends back a response
   4. REPL `ask()` gets the response and returns, printing it
   5. REPL uses `tell()` to send ActorExitRequest
   6. Hello actor gets the message and sends back a response (it doesn't matter to Hello that the message is an ActorExitRequest).
    7. REPL uses `ask()` to send 'hi' to the Hello actor
    8. The Hello actor is no longer present, so the message sent in step 7 is sent to the DeadLetterHandler, or it is discarded if there is no DeadLetterHandler
    9. REPL's `ask()` finds the message send by the Hello actor in step 6 on its queue and returns, printing it (this is probably the point where you were surprised)
   10. REPL's `ask()` sends a 'hi', but the failure and redirect in step 8 informed the REPL ActorSystem endpoint that the Hello actor address was dead, and there are also no more pending messages from Hello, so it immediately returns the None instead of also needing to wait for the 1 second timeout (which may also have surprised you).

The above is based on the assumption of what the Hello actor implementation is.  If your implementation is different and the above explanation does not apply, please let me know.  Regardless, thank you for the report: I'll add some additional documentation for the Quick Start to describe this subtle behavior characteristic.

Regards,
  Kevin

**Comment by Bazmundi** [comment]
Wow! Thanks for the detailed response.

Yes, sorry, you assumed correctly it was from the quick start.


Cheers,
B

On 26 Nov 2017 18:02, "Kevin Quick" <notifications@github.com> wrote:

Hi @Bazmundi <https://github.com/bazmundi>,

You didn't include the body of your Hello actor, so I'm assuming you are
using the one in the "Quick Start" documentation:

class Hello(Actor):
    def receiveMessage(self, message, sender):
        self.send(sender, 'Hello, World!')

There is a subtle interplay occurring here:

   - An actor is always called with the ActorExitRequest message. This
   allows it to perform shutdown activities, but when the receiveMessage
   method returns to the caller, the Actor will then be destroyed.
   - The messages sent to any other Actor, or to the external requestor are
   queued for the recipient.

Thus, what is happening in your report is:

   1. Hello actor is created
   2. REPL uses ask() to send 'hi' to the Hello actor and wait for a
   response
   3. Hello actor gets the message and sends back a response
   4. REPL ask() gets the response and returns, printing it
   5. REPL uses tell() to send ActorExitRequest
   6. Hello actor gets the message and sends back a response (it doesn't
   matter to Hello that the message is an ActorExitRequest).
   7. REPL uses ask() to send 'hi' to the Hello actor
   8. The Hello actor is no longer present, so the message sent in step 7
   is sent to the DeadLetterHandler, or it is discarded if there is no
   DeadLetterHandler
   9. REPL's ask() finds the message send by the Hello actor in step 6 on
   its queue and returns, printing it (this is probably the point where you
   were surprised)
   10. REPL's ask() sends a 'hi', but the failure and redirect in step 8
   informed the REPL ActorSystem endpoint that the Hello actor address was
   dead, and there are also no more pending messages from Hello, so it
   immediately returns the None instead of also needing to wait for the 1
   second timeout (which may also have surprised you).

The above is based on the assumption of what the Hello actor implementation
is. If your implementation is different and the above explanation does not
apply, please let me know. Regardless, thank you for the report: I'll add
some additional documentation for the Quick Start to describe this subtle
behavior characteristic.

Regards,
Kevin

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kquick/Thespian/issues/16#issuecomment-346988993>, or mute
the thread

**Comment by kquick** [comment]
Sounds good.  I've updated the text at http://thespianpy.com/doc/#hH-ff97e697-52e8-48e5-8682-86a4f90c750b, and I'm closing this issue, but please feel free to re-open it if you have suggestions for alternate wordings or related issues.
