### ISSUE TITLE
Make Thespian's internal logging threshold configurable

### ISSUE THREAD

**Issue by danielmitterdorfer** [kquick/Thespian#23]
I often use Thespian's internal log output to diagnose problems. Since 9c9ab7636cd0bf399950903ace7aec3a95134155 the log output is a bit silent unfortunately. 

For example, recently I investigated a message serialization problem which I would have expected to see in  Thespian's log file but the file was not even created. So I rolled back from 3.9.2 to 3.8.3 (which was the latest release that did not contain the commit above) and there I saw:

```
2018-05-14 13:10:10.625113 p10160 I    OUCH!  Error deserializing received data: Traceback (most recent call last):
  File "/Users/daniel/Projects/rally/.venv/lib/python3.6/site-packages/thespian-3.8.3-py3.6.egg/thespian/system/transport/TCPTransport.py", line 1431, in _addedDataToIncoming
    rdata, extra = inc.data
  File "/Users/daniel/Projects/rally/.venv/lib/python3.6/site-packages/thespian-3.8.3-py3.6.egg/thespian/system/transport/TCPTransport.py", line 185, in data
    def data(self): return self._rData.completed()
  File "/Users/daniel/Projects/rally/.venv/lib/python3.6/site-packages/thespian-3.8.3-py3.6.egg/thespian/system/transport/streamBuffer.py", line 80, in completed
    return self._deserialize(self._buf), self._extra
ModuleNotFoundError: No module named 'eventdata'
```

It would be great if we could make the logging threshold configurable with an environment variable similarly to `THESPLOG_FILE` and `THESPLOG_FILE_MAXSIZE` (e.g. `THESPLOG_THRESHOLD`?). If you agree with that, I'd be happy to provide a PR.

Besides, maybe such messages should be logged on "error" (or "warning") level?

**Comment by kquick** [comment]
A couple of thoughts on this (in no particular order):
* Yes, log verbosity was turned down a little in that patch, and the last change in there is the key change that you would want to set via a `THESPLOG_THRESHOLD` value.
* I'd be happy to accept a PR adding this control.
* Be aware that the environment variable would need to be in place when the Actor System was started up; a long-running system would not benefit from changes in the variable because each Actor (and the Admin) run in a separate process context and would therefore not benefit from any changes made to this environment variable value, and a complete restart of the Actor System would be needed to pick up any changes.
* The logging we are talking about here is the internal Thespian logging, not the general `logging` facility supported for Actors.  The latter, with its standard logging configuration, is still the best way for Actor-level logging and the internal Thespian logging was intended only for handling Thespian internals that couldn't be safely (or reasonably) handled via standard logging (which is routed through Actor forwarding to the logger Actor).  This is why this this configuration flexibility has not existed in the past: I usually intended to modify the code manually in the process of investigating a Thespian bug and had not expected this to be as useful to Thespian users.  That said, I have asked people reporting issues to modify this multiple times, so having an environment variable to handle that would be convenient.
* In this particular case, the log output was originally designed to debug the `streamBuffer` implementation, although the particular error case you see above is more of an Actor-level error than a Thespian internal error, so changing it to ERROR is good, and it is probably better logged via the standard `logging` facility; feel free to add this in your PR if you would like, or I can do this if you would prefer.
* The particular error indicated by the above usually happens when the source code for the target Actor and the source Actor are out-of-sync.  Thespian's support for loadable sources is intended to mitigate this issue (and the Thespian Director helps manage the loadable sources).  I know you have other reasons for not using this particular capability of Thespian, but I thought it was worth pointing out that it helps address this problem you encountered.

Thanks, Daniel!

**Comment by danielmitterdorfer** [comment]
Thanks Kevin for your thoughtful answer!

I am aware of most points that you mentioned, specifically that this is really Thespian's internal log and that picking up a new log level requires a restart of the actor system. 

I also know how that specific error happened: Rally allows extension modules which get loaded dynamically by an actor. In that specific case one actor has loaded such an extension module, it raised a custom exception which we forwarded to the parent actor which could not deserialize the exception as it did not load the module. We fixed the original issue already but during my analysis I wondered why nothing showed up in the internal actor system log, hence this ticket.

W.r.t changing the log level for the `streamBuffer` implementation: I can include the change of the log level in my PR as well.
