### ISSUE TITLE
Low performance sending low latency messages between actors

### ISSUE THREAD

**Issue by jonatel** [kquick/Thespian#25]
I using Thespian to develop an application to consume low latency data via sockets. I had created initially two actors: one consumer (socket client connection) and the handler. Testing, I detected some delays between the time used to send one message in the consumer (Actor1) and when this message has arrived in the handler (Actor2).

To test that, I had used the following code.

```
from thespian.actors import ActorSystem, Actor
import time


class Actor1(Actor):
    def receiveMessage(self, handler, sender):
        # benchmark
        data = {'tic': time.perf_counter(), 'lim': 10000}
        print('Elapsed Time to process {} messages'.format(data['lim']))
        for i in range(data['lim']):
            self.send(handler, data)
        # perf
        toc = time.perf_counter() - data['tic']
        print('Actor 1: {} sec'.format(round(toc, 3)))
        # self.actorSystemShutdown()


class Actor2(Actor):
    def __init__(self):
        self.msg_count = 0

    def receiveMessage(self, data, sender):
        self.msg_count += 1
        if self.msg_count == data['lim']:
            toc = time.perf_counter() - data['tic']
            print('Actor 2: {} sec'.format(round(toc, 3)))

def main():
    asys = ActorSystem('multiprocTCPBase')
    consumer = asys.createActor(Actor1)
    handler = asys.createActor(Actor2)
    asys.tell(consumer, handler)

if __name__ == '__main__':
    main()
```

**Results:**
```
Elapsed Time to process 10 messages
Actor 1: 0.002 sec
Actor 2: 0.008 sec

Elapsed Time to process 100 messages
Actor 1: 0.019 sec
Actor 2: 0.099 sec

Elapsed Time to process 1000 messages
Actor 1: 0.131 sec
Actor 2: 0.769 sec

Elapsed Time to process 10000 messages
Actor 1: 1.219 sec
Actor 2: 7.608 sec

Elapsed Time to process 100000 messages
Actor 1: 22.012 sec
Actor 2: 91.419 sec
```

Looking these results, There is something wrong or missing that I have in my code?, or there is another faster way to send the messages between actors? Also, there is any other benchmark that help us to analyze the performance[ commented in the documentation.](https://github.com/godaddy/Thespian/blob/master/doc/using.org#performance)

**Comment by kquick** [comment]
I don't think there is anything significantly wrong with your code (I would probably make a couple of small adjustments, but nothing that would impact the timing).

One item to note is that the `self.send()` is asynchronous, so the times reported by Actor1 represent just the time needed to queue the count of outbound messages, and the actual transmission will occur after the reported time for Actor1.

Within the context of performance (from the section you reference), throughput (large messages) is generally of higher priority than latency (large counts of packets), so the particular test you are performing represents the lowest priority/worst case scenario for the implementation.  The limiting elements documented in that section don't appear to be significantly affecting the results, based on initial testing.

I would like to investigate a little further, but it would help to know what you performance you are expecting so that I can determine if there are reasonable adjustments to the limiter or the code that can achieve your desired target.

**Comment by JocOnat** [comment]
Thanks for you response Kevin. I really are not expecting any specific performance, but I are wondering why the process to only send messages between two actors is consuming a lot of time. I did a test to process the messages sent by the Actor1 using Actor2 and using a function. Comparing the time used to process around 10000 messages, using a function is faster ~100 times than using the Actor2. Also I tried using the [Actor Troupe Support](https://github.com/godaddy/Thespian/blob/master/doc/using.org#actor-troupe-support), but the processing time increase.

I would be very grateful is you found another way to reduce this time, or you believe that this something normal in the actor model using asynchronous communication.

**Comment by kquick** [comment]
It's the focus on reliability (especially in the presence of errors) that adds a fair amount of overhead beyond a simple process-to-process exchange.  A native actor implementation (e.g. Erlang), and especially one that doesn't have to span multiple systems can achieve some very high performance due to a very focused approach, but building on top of the Python runtime and supporting a distributed environment adds some overhead, unfortunately.

The troupe will be slower in this case because it essentially adds another layer: the original troupe actor becomes a multiplexer that creates individual workers and forwards messages to those workers, so you were doubling the number of message transmissions involved.  The troupe works very well for horizontal scaling when the bottleneck is the processing of the messages within the Actor (as opposed to your case, where the bottleneck is the exchange of messages between the Actors). Adding a `time.sleep(1)` after the increment of `msgcount` in Actor2 to simulate local processing would demonstrate the advantage of the troupe (although it would require other changes, because now the messages are distributed across troupe members and so none of the individual members would ever match `self.msg_count == data['lim']`).

I will  look into the overhead (and do further verification of any impact of the rate limiting) to see if there is something egregious that can be eliminated, but I don't know that I'll achieve an improvement of two orders of magnitude, at least in the near term efforts.

**Comment by kquick** [comment]
Hi @JocOnat ,

There is currently no system base in Thespian that provides transport security directly, so you would probably need to use the VPN method.  This is really only needed when you communicate between multiple physical systems; for actors communicating on the same host you would not need extra transport security.

If you have actors on separate hosts that are communicating and you want the security, you would use a VPN.  You would independently setup a VPN for those host systems that will be communicating via actors, and the VPN will introduce a separate IP address space for those systems.  You would then specify the ConventionManager address using the VPN address.  All of the connections would then be made over the VPN, and the VPN would provide the transport security.

**Comment by kquick** [comment]
Closing under the assumption that the above response has resolved this issue.  If this is not correct, please feel free to re-open this issue.

Thanks!
  Kevin
