### ISSUE TITLE
Logging error when using RotatingFileHandler

### ISSUE THREAD

**Issue by andatt** [kquick/Thespian#34]
Hi Kevin

Sorry to come back to you again so soon. I am having another issue with logging, this time using a rotating file handler. Mostly it seems to work fine in my tests. However there is one test which produces an error. When I change the logging handler back to FileHandler then the code runs with no issues.

The code which produces the issues is as follows:

```
class GrandParentActor(ActorTypeDispatcher):
    pass

class ParentActor(GrandParentActor):

    def receiveMessage(self, msg, sender):
        pass

@troupe(max_count=30)
class TroupeActor30(ParentActor):
    pass


messages = [{}] * 500
live_actor = actor_system.createActor(TroupeActor30)

for message in messages:
    self.act_sys.tell(live_actor, message)
````

this produces an error in the logs of:

```
WARNING  2018-12-19 12:10:35,667 ActorAddr-(T|:41051) => Actor tests.concept.test_data_structures.test_actors.TroupeActor30 @ ActorAddr-(T|:41051) retryable exception on message Poison<_TroupeWork(from=ActorAddr-(T|:43165), msg={})>: Traceback (most recent call last):
  File "/Thespian/thespian/system/actorManager.py", line 156, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(msg, envelope.sender)
  File "/Thespian/thespian/troupe.py", line 141, in manageTroupe
    message.orig_sender)
  File "/Thespian/thespian/troupe.py", line 143, in manageTroupe
    r = self._orig_receiveMessage(message, sender)
  File "/Thespian/thespian/troupe.py", line 143, in manageTroupe
    r = self._orig_receiveMessage(message, sender)
  File "/Thespian/thespian/troupe.py", line 143, in manageTroupe
...
```

This traceback then goes on to hundreds of lines till it reaches maximum recursion depth.

I also found that if I modify the code to remove the multiple inheritance:

```
@troupe(max_count=30)
class TroupeActor30(ActorTypeDispatcher):
    def receiveMessage(self, msg, sender):
        pass

messages = [{}] * 500
live_actor = actor_system.createActor(TroupeActor30)

for message in messages:
    actor_system.tell(live_actor, message)
````

Then it works as expected without error. Logging config in all cases is:

```
{
        'version': 1,
        'formatters': {
            'normal': {'format': '%(levelname)-8s %(asctime)s %(message)s'},
            'actor': {'format': '%(levelname)-8s %(asctime)s %(actorAddress)s => %(message)s'}
        },
        'filters': {
            'isActorLog': {'()': ActorLogFilter},
            'notActorLog': {'()': NotActorLogFilter}
        },
        'handlers': {
                        'h1': {
                                'class': 'logging.handlers.RotatingFileHandler',
                                'filename': log_file_path_1,
                                'formatter': 'normal',
                                'filters': ['notActorLog'],
                                'level': logging.INFO,
                                'maxBytes': 50000000,
                                "backupCount": 5
                        },

                        'h2': {
                                'class': 'logging.handlers.RotatingFileHandler',
                                'filename': log_file_path_2,
                                'formatter': 'actor',
                                'filters': ['isActorLog'],
                                'level': logging.INFO,
                                'maxBytes': 50000000,
                                "backupCount": 5
                        }
                    },

        'loggers': {'': {'handlers': ['h1', 'h2'], 'level': logging.DEBUG}}
    }
```
This is inside docker again in case that makes any difference. Am I doing something stupid here?

**Comment by kquick** [comment]
Hi @andatt,
No problem with additional issues: I'm glad you are using Thespian and happy to help with any problems.

In this case, I cannot reproduce your issue.  I did have to make some modifications to the code sample above that produces the issue (I initialize the `ActorSystem` in a main function before creating the `TroupeActor30`, and reconciled your `actor_system` with `self.act_sys`).  When I run this, I get essentially no logging (other than the "ActorSystem Logging Shutdown" at the end).

A couple of additional notes
  *  The `@troupe` decorator will try to replace the original `receiveMessage` method so make sure that doesn't cause you problems (especially with other decorators that would try to do similar things).
  * The `ActorTypeDispatcher` has its own `receiveMessage` and expects its subclasses to use `receiveMsg_TYPE` methods, so the `receiveMessage` method in `ParentActor` is replacing the type dispatching provided by `GrandParentActor` with a simple message discard.

I've attached my version of the test so you can try it locally and compare it with your actual code to see what might be causing your problems (with the .txt extension so that github will accept it).

[issue_34.txt](https://github.com/kquick/Thespian/files/2697697/issue_34.txt)

**Comment by kquick** [comment]
Hi @andatt,

If you get a chance, I'm curious as to whether the above is still a problem for you with the latest 3.9.8 release.

Thanks,
  Kevin

**Comment by andatt** [comment]
Hi Kevin

This all looks good now! Fixes seem to have resolved this problem too.

Thanks!

Andrew

**Comment by kquick** [comment]
Excellent news, thank you!
